# Generated by Django 3.2.8 on 2021-10-19 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
    ]
